# workflow 이름
name: ci

# 워크플로우를 실행시키는 event
on: [push]

jobs:
  # 의존성 설치
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Restore node modules from cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: MBTI/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('MBTI/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: MBTI # 이 부분을 수정한 것

  # lint 확인 및 수정
  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Restore node modules from cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: MBTI/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('MBTI/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies (if not cached)
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: MBTI # 이 부분을 수정한 것

      - name: Run lint
        run: npm run lint
        working-directory: MBTI # 이 부분을 수정한 것

  # 테스트 검증
  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Restore node modules from cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: MBTI/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('MBTI/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies (if not cached)
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: MBTI # 이 부분을 수정한 것

      - name: Run tests
        run: npm run test
        working-directory: MBTI # 이 부분을 수정한 것

  # React Build
  build:
    runs-on: ubuntu-latest
    needs: [install-dependencies, lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Restore node modules from cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: MBTI/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('MBTI/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies (if not cached)
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: MBTI # 이 부분을 수정한 것

      - name: Run Build
        run: npm run build
        working-directory: MBTI # 이 부분을 수정한 것
